smartMotor.motorStart(smartMotor.MotorPort.M5, smartMotor.MotorDirection.Clockwise, 100)
smartMotor.motorStart(smartMotor.MotorPort.M8, smartMotor.MotorDirection.Counterclockwise, -100)
smartMotor.motorStop(smartMotor.MotorPort.M5)

smartMotor.motorReset(smartMotor.MotorPort.M6)
smartMotor.motorReset(smartMotor.MotorPort.M6, smartMotor.WaitMode.Wait)
smartMotor.motorReset(smartMotor.MotorPort.M6, smartMotor.WaitMode.NoWait)
smartMotor.motorMoveAbsolute(smartMotor.MotorPort.M6, 0, -100)
smartMotor.motorMoveAbsolute(smartMotor.MotorPort.M6, 360, 100)
smartMotor.motorMoveAbsolute(smartMotor.MotorPort.M6, 180, 60, smartMotor.MotorTurnMode.ShortestPath)
smartMotor.motorMoveAbsolute(smartMotor.MotorPort.M6, 180, 60, smartMotor.MotorTurnMode.ShortestPath, smartMotor.WaitMode.Wait)
smartMotor.motorMoveAbsolute(smartMotor.MotorPort.M6, 90, 50, smartMotor.MotorTurnMode.Clockwise, smartMotor.WaitMode.NoWait)
smartMotor.motorMoveAbsolute(smartMotor.MotorPort.M6, 270, 50, smartMotor.MotorTurnMode.Counterclockwise, smartMotor.WaitMode.Wait)
smartMotor.motorMoveRelative(smartMotor.MotorPort.M7, 0, -100)
smartMotor.motorMoveRelative(smartMotor.MotorPort.M7, 360, 100)
smartMotor.motorMoveRelative(smartMotor.MotorPort.M7, 90, 50, smartMotor.MotorDirection.Clockwise)
smartMotor.motorMoveRelative(smartMotor.MotorPort.M7, 1, 50, smartMotor.MotorDirection.Counterclockwise, smartMotor.MotorMoveUnit.Circle)
smartMotor.motorMoveRelative(smartMotor.MotorPort.M7, 90, 50, smartMotor.MotorDirection.Clockwise, smartMotor.MotorMoveUnit.Degree, smartMotor.WaitMode.Wait)
smartMotor.motorMoveRelative(smartMotor.MotorPort.M7, 1, 50, smartMotor.MotorDirection.Counterclockwise, smartMotor.MotorMoveUnit.Circle, smartMotor.WaitMode.NoWait)
smartMotor.motorMoveRelative(smartMotor.MotorPort.M7, 2, 50, smartMotor.MotorDirection.Clockwise, smartMotor.MotorMoveUnit.Second, smartMotor.WaitMode.Wait)

smartMotor.robotSetWheelDiameter(0)
smartMotor.robotSetWheelDiameter(10000)
smartMotor.robotSetWheelDiameter(62)
smartMotor.robotSetMotors(smartMotor.MotorPort.M5, smartMotor.MotorPort.M6)
smartMotor.robotTurn(-360, 0, smartMotor.AccelLevel.Slow)
smartMotor.robotTurn(90, 50, smartMotor.AccelLevel.Medium)
smartMotor.robotTurn(360, 100, smartMotor.AccelLevel.Fast, smartMotor.WaitMode.Wait)
smartMotor.robotTurn(-90, 50, smartMotor.AccelLevel.Medium, smartMotor.WaitMode.NoWait)
while (!smartMotor.robotIsIdle()) {
    basic.pause(10)
}
smartMotor.robotTurn(90, 50, smartMotor.AccelLevel.Medium, smartMotor.WaitMode.NoWait)
basic.pause(100)
smartMotor.robotStop()
smartMotor.robotDriveStraight(smartMotor.DriveDirection.Forward, 100, smartMotor.DriveMode.Millimeters, 50, smartMotor.AccelLevel.Medium, smartMotor.WaitMode.Wait)
smartMotor.robotDriveStraight(smartMotor.DriveDirection.Backward, 10, smartMotor.DriveMode.Seconds, 35, smartMotor.AccelLevel.Slow, smartMotor.WaitMode.Wait)
smartMotor.robotDriveStraight(smartMotor.DriveDirection.Forward, 360, smartMotor.DriveMode.Degrees, 85, smartMotor.AccelLevel.Fast, smartMotor.WaitMode.Wait)
smartMotor.robotDriveStraight(smartMotor.DriveDirection.Forward, 10000, smartMotor.DriveMode.Millimeters, 60, smartMotor.AccelLevel.Medium, smartMotor.WaitMode.NoWait)
basic.pause(100)
smartMotor.robotStop()
smartMotor.robotTurn(0, 50, smartMotor.AccelLevel.Medium)
smartMotor.robotDriveStraight(smartMotor.DriveDirection.Forward, 0, smartMotor.DriveMode.Millimeters, 50, smartMotor.AccelLevel.Medium, smartMotor.WaitMode.Wait)
smartMotor.robotStop()

let motorSpeed = smartMotor.motorGetSpeed(smartMotor.MotorPort.M5)
let motorAbsoluteAngle = smartMotor.motorGetAbsoluteAngle(smartMotor.MotorPort.M6)
let motorRelativeAngle = smartMotor.motorGetRelativeAngle(smartMotor.MotorPort.M7)

smartMotor.resetGyroAngle()
let pitchSpeed = smartMotor.readGyroAngularSpeed(smartMotor.GyroAxis.Pitch)
let yawAngle = smartMotor.readGyroAngle(smartMotor.GyroAxis.Yaw)
let rollAngle = smartMotor.readGyroAngle(smartMotor.GyroAxis.Roll)
let firmwareVersion = smartMotor.readVersion()

basic.showNumber(motorSpeed + motorAbsoluteAngle + motorRelativeAngle + pitchSpeed + yawAngle + rollAngle)
basic.showString(firmwareVersion)
